### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by jroakes** [zakrywilson/abstractive-summarization#1]
This is the demo file that worked for me

```
#!/bin/bash

CLASSPATH="-cp .:lib/slf4j-api-1.7.14.jar:lib/slf4j-simple-1.7.14.jar:lib/stanford-openie.jar:lib/stanford-openie-models.jar:lib/stanford-corenlp-3.5.2-models.jar:lib/stanford-corenlp-3.5.2.jar:bin"

# Remove *.class files if they exist
if [ -e *.class ]; then
  rm *.class
fi

# Run program
javac $CLASSPATH *.java
java $CLASSPATH Manager

# Clean up after running
sudo rm *.class
```

The one given does not work. 
ie (Manager could not be found and java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory errors)

 Also, I think that in setup if the path is left blank it should execute to the current directory instead of needing to build a new one.

**Comment by zakrywilson** [comment]
I really appreciate the feedback! I found there was an issue with the hosting site for the JARs. I moved them to Dropbox and they seem to be working better. 

I also took your advice and made it so the setup script installs in the working directory if no directory is specified.

I was, too, getting that error; but since I switched to Dropbox and made a few other changes to the setup script, the demo script is working for me. I'd be interested to see how it works for you on your box.

Again, thanks for the feedback––it's very much appreciated!
